x-common: &common
  image: "node:20.8.1"
  when:
    - event: pull_request
  environment:
    - NEXT_PUBLIC_API_BASE_URL=http://localhost:3000

pipeline:
  setup:
    <<: *common
    commands:
      - npm ci --prefer-offline
  build-and-lint:
    <<: *common
    group: build
    commands:
      # NOTE: a build step is needed before linting since
      # Next generates the type file after buildling or running the
      # dev server.
      - npm run build
      - npm run lint
      - npm run tsc
  prettier:
    <<: *common
    group: build
    commands:
      - npm run prettier:check -- --support-info
  sass-lint:
    <<: *common
    group: build
    commands:
      - npm run stylelint
  js-test:
    <<: *common
    group: build
    commands:
      - npm run test
